export const laptops = [
  {
    id: "laptol-1",
    name: "Laptop Asus Rog Strix Intel Core i9-14900Hx, 16GB, 1Tb, 16'' FHD,Video RTX 4060, Win 11 Pro",
    price: "S/ 1,469",
    originalPrice: "S/ 1,699",
    brand: "Asus",
    rating: 4,
    reviews: 128,
    discount: 15,
    stock: 5,
    freeShipping: true,
    specs: ["Intel Core i9", "16GB RAM", "1TB SSD", "RTX 4060"],
    installments: "12x S/ 122.42 sin interés",
    image: "/productos/header_ofert1.png?height=300&width=300",
  },
  {
    id: "laptol-2",
    name: "Gamer HP Intel Core i7 RTX 3050 16GB 512 GB SSD Victus 12va Gen 15.6'' 15-fa0007la W11",
    price: "S/ 1,499",
    originalPrice: "S/ 1,599",
    brand: "HP",
    rating: 5,
    reviews: 89,
    discount: 8,
    stock: 12,
    freeShipping: true,
    isBestSeller: true,
    specs: ["Intel Core i7", "16GB RAM", "512GB SSD", "RTX 3050"],
    installments: "18x S/ 81.61 sin interés",
    image: "/productos/header_ofert2.png?height=300&width=300",
  },
  {
    id: "laptol-3",
    name: "LAPTOP GAMER ACER NITRO V15 ANV15-51-711U i7 13° GEN. 15.6 FHD IPS 144Hz 16GB 512GB RTX4050 6GB W11",
    price: "S/ 1,549",
    originalPrice: "S/ 1,549",
    brand: "Acer",
    rating: 4,
    reviews: 67,
    discount: 5,
    stock: 8,
    freeShipping: true,
    specs: ["Intel Core i7", "16GB RAM", "512GB SSD", "RTX 4050"],
    installments: "24x S/ 61.21 sin interés",
    image: "/productos/header_ofert3.png?height=300&width=300",
  },
  {
    id: "laptol-4",
    name: "ACER Nitro V15 ANV15-51-56GH Ci5 13420H/ 8Gb Ram/ 512GB SSD/ RTX 3050 6GB/ 15.6”FHD W.11 - CSI",
    price: "S/ 1,469",
    originalPrice: "S/ 1,799",
    brand: "Acer",
    rating: 5,
    reviews: 156,
    discount: 18,
    stock: 3,
    freeShipping: true,
    isNew: true,
    specs: ["Intel Core i5", "8GB RAM", "512GB SSD", "RTX 3050"],
    installments: "6x S/ 244.83 sin interés",
    image: "/productos/header_ofert4.png?height=300&width=300",
  },
];

export const audifonos = [
  {
    id: "audifono-1",
    name: "Audifono Redragon Zeus X PRO RGB H510-PRO-WL Wireless BLACK",
    price: "s/ 89.99",
    originalPrice: "s/ 119.99",
    brand: "Redragon",
    rating: 5,
    reviews: 234,
    discount: 25,
    stock: 15,
    freeShipping: true,
    isBestSeller: true,
    specs: ["Bluetooth 5.0", "RGB lighting", "40-hour battery life"],
    installments: "3x s/ 29.99 sin interés",
    image: "/productos/audifonos/audifono1.png?height=200&width=200",
  },
  {
    id: "audifono-2",
    name: "Audífonos Bluetooth Haylou S30 PRO ANC Hybrid Hi-Res - Blanco",
    price: "s/ 179.99",
    originalPrice: "s/ 199.99",
    brand: "Haylou",
    rating: 4,
    reviews: 167,
    discount: 10,
    stock: 8,
    freeShipping: true,
    specs: ["Active Noise Cancellation", "Hi-Res Audio", "Touch controls"],
    installments: "6x s/ 29.99 sin interés",
    image: "/productos/audifonos/audifono2.png?height=200&width=200",
  },
  {
    id: "audifono-3",
    name: "Audífonos Bluetooth Haylou S30 PRO ANC Hybrid Hi-Res - Negro",
    price: "s/ 129.99",
    originalPrice: "s/ 149.99",
    brand: "Haylou",
    rating: 4,
    reviews: 198,
    discount: 13,
    stock: 12,
    freeShipping: true,
    specs: ["Bluetooth 5.1", "Low latency", "Dual microphone"],
    installments: "4x s/ 32.49 sin interés",
    image: "/productos/audifonos/audifono3.png?height=200&width=200",
  },
  {
    id: "audifono-4",
    name: "AUDIFONOS GAMER COMBAT NEGROAZUL",
    price: "s/ 149.99",
    originalPrice: "s/ 169.99",
    brand: "Combat",
    rating: 5,
    reviews: 145,
    discount: 12,
    stock: 6,
    freeShipping: true,
    isNew: true,
    specs: ["50mm drivers", "Noise isolation", "Adjustable headband"],
    installments: "5x s/ 29.99 sin interés",
    image: "/productos/audifonos/audifono4.png?height=200&width=200",
  },
  {
    id: "audifono-5",
    name: "Corsair HS80 RGB Wireless",
    price: "s/ 149.99",
    originalPrice: "s/ 179.99",
    brand: "Corsair",
    rating: 4,
    reviews: 112,
    discount: 17,
    stock: 9,
    freeShipping: true,
    specs: [
      "Dolby Atmos",
      "Custom-tuned 50mm drivers",
      "Up to 20 hours battery life",
    ],
    installments: "6x s/ 24.99 sin interés",
    image: "/productos/audifonos/audifono5.png?height=200&width=200",
  },
  {
    id: "audifono-6",
    name: "Audífonos Bluetooth Haylou S30 PRO ANC Hybrid Hi-Res",
    price: "s/ 199.99",
    originalPrice: "s/ 229.99",
    brand: "Haylou",
    rating: 5,
    reviews: 78,
    discount: 13,
    stock: 4,
    freeShipping: true,
    specs: ["Bluetooth 5.2", "IPX5 water resistance", "Touch controls"],
    installments: "8x s/ 24.99 sin interés",
    image: "/productos/audifonos/audifono6.png?height=200&width=200",
  },
];

export const televisores = [
  {
    id: "televisor-1",
    name: 'Samsung OLED 55" QN90A Neo QLED 4K',
    price: "s/ 1,299.99",
    originalPrice: "s/ 1,499.99",
    brand: "Samsung",
    rating: 5,
    reviews: 89,
    discount: 13,
    stock: 7,
    freeShipping: true,
    isBestSeller: true,
    specs: [
      "Neo Quantum Processor 4K",
      "Quantum HDR 32X",
      "120Hz refresh rate",
    ],
    installments: "12x s/ 108.33 sin interés",
    image: "/productos/televisiones/tv1.png?height=200&width=200",
  },
  {
    id: "televisor-2",
    name: 'LG OLED 65" C1 Series 4K Smart TV',
    price: "s/ 1,799.99",
    originalPrice: "s/ 1,999.99",
    brand: "LG",
    rating: 5,
    reviews: 156,
    discount: 10,
    stock: 5,
    freeShipping: true,
    specs: ["α9 Gen4 AI Processor", "Dolby Vision IQ", "HDMI 2.1"],
    installments: "18x s/ 99.99 sin interés",
    image: "/productos/televisiones/tv2.png?height=200&width=200",
  },
  {
    id: "televisor-3",
    name: 'Sony OLED 55" A80J Bravia XR',
    price: "s/ 1,399.99",
    originalPrice: "s/ 1,599.99",
    brand: "Sony",
    rating: 4,
    reviews: 134,
    discount: 12,
    stock: 8,
    freeShipping: true,
    isNew: true,
    specs: ["Cognitive Processor XR", "XR OLED Contrast", "Google TV"],
    installments: "15x s/ 93.33 sin interés",
    image: "/productos/televisiones/tv3.png?height=200&width=200",
  },
  {
    id: "televisor-4",
    name: 'TCL QLED 50" C825 Mini LED 4K',
    price: "s/ 899.99",
    originalPrice: "s/ 1,099.99",
    brand: "TCL",
    rating: 4,
    reviews: 67,
    discount: 18,
    stock: 12,
    freeShipping: true,
    specs: ["Quantum Dot technology", "Mini LED backlight", "120Hz VRR"],
    installments: "9x s/ 99.99 sin interés",
    image: "/productos/televisiones/tv4.png?height=200&width=200",
  },
  {
    id: "televisor-5",
    name: 'samsung QLED 55" Q80A 4K Smart TV',
    price: "s/ 999.99",
    originalPrice: "s/ 1,199.99",
    brand: "Samsung",
    rating: 4,
    reviews: 98,
    discount: 17,
    stock: 10,
    freeShipping: true,
    specs: [
      "Quantum Dot Wide Color",
      "Full Array Local Dimming",
      "Dolby Vision",
    ],
    installments: "10x s/ 99.99 sin interés",
    image: "/productos/televisiones/tv5.png?height=200&width=200",
  },
  {
    id: "televisor-6",
    name: 'samsung QLED 65" QN85A 4K Smart TV',
    price: "s/ 1,199.99",
    originalPrice: "s/ 1,399.99",
    brand: "Samsung",
    rating: 5,
    reviews: 45,
    discount: 14,
    stock: 6,
    freeShipping: true,
    specs: ["P5 AI Perfect Picture", "3-sided Ambilight", "Android TV"],
    installments: "12x s/ 99.99 sin interés",
    image: "/productos/televisiones/tv6.png?height=200&width=200",
  },
];

export const Sillas = [
  {
    id: "silla-1",
    name: "Silla Gamer Reclinación 155° con Posapies y Masajeador",
    price: "s/ 429.99",
    originalPrice: "s/ 449.99",
    brand: "Codari",
    rating: 5,
    reviews: 267,
    discount: 4,
    stock: 15,
    freeShipping: true,
    isBestSeller: true,
    specs: ["Reclinación 155°", "Posapies ajustable", "Masajeador incorporado"],
    installments: "12x s/ 35.83 sin interés",
    image: "/productos/sillas/silla1.png?height=200&width=200",
  },
  {
    id: "silla-2",
    name: "Silla Gamer Reclinación 155° con Posapies y Masageador",
    price: "s/ 379.99",
    originalPrice: "s/ 429.99",
    brand: "Codari",
    rating: 4,
    reviews: 189,
    discount: 12,
    stock: 11,
    freeShipping: true,
    specs: ["Reclinación 155°", "Posapies ajustable", "Diseño ergonómico"],
    installments: "10x s/ 37.99 sin interés",
    image: "/productos/sillas/silla2.png?height=200&width=200",
  },
  {
    id: "silla-3",
    name: "Silla Gamer Kuzler Con Masajeador Lumbar Color Rosa RIK-101R",
    price: "s/ 449.99",
    originalPrice: "s/ 499.99",
    brand: "Kuzler",
    rating: 5,
    reviews: 123,
    discount: 10,
    stock: 8,
    freeShipping: true,
    isNew: true,
    specs: ["Reclinación 155°", "Posapies ajustable", "Masajeador lumbar"],
    installments: "15x s/ 29.99 sin interés",
    image: "/productos/sillas/silla3.png?height=200&width=200",
  },
  {
    id: "silla-4",
    name: "Silla Gamer Kuzler Negra con masajeador lumbar reposapiés y base metálica",
    price: "s/ 199.99",
    originalPrice: "s/ 249.99",
    brand: "Kuzler",
    rating: 4,
    reviews: 234,
    discount: 20,
    stock: 18,
    freeShipping: true,
    specs: [
      "Reclinación 155°",
      "Posapies ajustable",
      "Base metálica resistente",
    ],
    installments: "6x s/ 33.33 sin interés",
    image: "/productos/sillas/silla4.png?height=200&width=200",
  },
  {
    id: "silla-5",
    name: "Silla Gamer Extingtion Sapp Gamuza-Cuerina Color Blanco",
    price: "s/ 279.99",
    originalPrice: "s/ 329.99",
    brand: "Extingtion",
    rating: 4,
    reviews: 156,
    discount: 15,
    stock: 13,
    freeShipping: true,
    specs: ["Reclinación 155°", "Posapies ajustable", "Diseño moderno"],
    installments: "8x s/ 34.99 sin interés",
    image: "/productos/sillas/silla5.png?height=200&width=200",
  },
  {
    id: "silla-6",
    name: "Silla Gamer Con Luces RGB Titan Con Masajeador Reposapiés 135° Blanco",
    price: "s/ 199.99",
    originalPrice: "s/ 229.99",
    brand: "Titan",
    rating: 4,
    reviews: 178,
    discount: 13,
    stock: 16,
    freeShipping: true,
    specs: [
      "Reclinación 135°",
      "Luces RGB personalizables",
      "Masajeador lumbar",
    ],
    installments: "7x s/ 28.57 sin interés",
    image: "/productos/sillas/silla6.png?height=200&width=200",
  },
];

// Ofertas Flash
export const flashDeals = [
  {
    id: "lll5",
    name: 'Laptop Lenovo Legion 5, Amd Ryzen 5 5600H, 8GB DDR4, SSD 512Gb, 15.6" FHD ',
    price: "S/ 2500",
    originalPrice: "S/ 3000",
    brand: "Lenovo",
    rating: 5,
    reviews: 345,
    discount: 17,
    stock: 3,
    freeShipping: true,
    timeLeft: "2h 15m",
    specs: ["M1 chip", "10.9-inch display", "12MP cameras"],
    image: "/productos/ofert1.png?height=200&width=200",
    installments: "12x S/ 208.33 sin interés",
  },
  {
    id: "tgl6213",
    name: "Teclado Gamer Marca Logitech G213 Prodigy Con Iluminación RGB, Black, Alámbrico - USB",
    price: "S/ 222.99",
    originalPrice: "S/ 249.99",
    brand: "Logitech",
    rating: 5,
    reviews: 189,
    discount: 17,
    stock: 2,
    freeShipping: true,
    timeLeft: "1h 45m",
    specs: ["M2 chip", "13.6-inch display", "18-hour battery"],
    image: "/productos/ofert2.png?height=200&width=200",
    installments: "12x S/ 208.33 sin interés",
  },
  {
    id: "cgha06",
    name: "Case Gamer Halion Aries 06 Con Fuente de 600W, 4 LED-ARGB, Vidrio Templado, Black",
    price: "S/ 799.99",
    originalPrice: "S/ 899.99",
    brand: "Halion",
    rating: 5,
    reviews: 567,
    discount: 12,
    stock: 1,
    freeShipping: true,
    timeLeft: "3h 30m",
    specs: ["A16 Bionic chip", "6.1-inch display", "48MP camera"],
    image: "/productos/ofert3.png?height=200&width=200",
    installments: "12x S/ 208.33 sin interés",
  },
];

export const categories = [
  {
    id: "laptops",
    title: "Laptops Gaming",
    icon: "🎮",
    productCount: 156,
    image: "/productos/categorias/cat1.png?height=100&width=100",
  },
  {
    id: "smartphones",
    title: "Smartphones",
    icon: "📱",
    productCount: 234,
    image: "/productos/categorias/cat2.png?height=100&width=100",
  },
  {
    id: "audifonos",
    title: "Audífonos",
    icon: "🎧",
    productCount: 89,
    image: "/productos/categorias/cat3.png?height=100&width=100",
  },
  {
    id: "televisores",
    title: "Televisores",
    icon: "📺",
    productCount: 67,
    image: "/productos/categorias/cat4.png?height=100&width=100",
  },
  {
    id: "lsmartwatches",
    title: "Smartwatches",
    icon: "⌚",
    productCount: 45,
    image: "/productos/categorias/cat5.png?height=100&width=100",
  },
  {
    id: "sillas",
    title: "Sillas",
    icon: "🔌",
    productCount: 178,
    image: "/productos/categorias/cat6.png?height=100&width=100",
  },
];

export const brandLogos = [
  { id: "log", name: "Logitech", src: "/productos/marcas/logo1.png" },
  { id: "sam", name: "Samsung", src: "/productos/marcas/logo2.png" },
  { id: "hyp", name: "HyperX", src: "/productos/marcas/logo3.png" },
  { id: "asu", name: "Asus", src: "/productos/marcas/logo4.png" },
];

export const relatedProducts = [
  {
    name: "iPhone 15 Pro 128GB",
    price: "$999",
    originalPrice: "$1,099",
    rating: 4.7,
    reviews: 1234,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    name: "AirPods Pro (2ª gen)",
    price: "$249",
    originalPrice: "$279",
    rating: 4.9,
    reviews: 5678,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    name: "MagSafe Charger",
    price: "$39",
    originalPrice: "$49",
    rating: 4.5,
    reviews: 890,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    name: "iPhone 15 Pro Max Case",
    price: "$59",
    originalPrice: "$79",
    rating: 4.6,
    reviews: 456,
    image: "/placeholder.svg?height=200&width=200",
  },
];

export const slides = [
  {
    id: 1,
    category: "iPhone 15 Pro Max",
    title: "TECNOLOGÍA\nQUE IMPACTA",
    description:
      "Explora el futuro con nuestros productos de última generación que transforman tu experiencia digital.",
    price: "s/ 4,999.00",
    image: "/inicio/head.png?height=500&width=600",
    buttonText: "Ver Detalles",
  },
  {
    id: 2,
    category: "MacBook Pro M3",
    title: "POTENCIA\nSIN LÍMITES",
    description:
      "Experimenta el rendimiento profesional con el nuevo chip M3 que revoluciona tu productividad.",
    price: "s/ 5,999.00",
    image: "/inicio/head2.png?height=500&width=600",
    buttonText: "Descubrir Más",
  },
  {
    id: 3,
    category: "AirPods Pro",
    title: "SONIDO\nINMERSIVO",
    description:
      "Sumérgete en una experiencia auditiva única con cancelación de ruido activa de nueva generación.",
    price: "s/ 999.00",
    image: "/inicio/head3.png?height=500&width=600",
    buttonText: "Escuchar Ahora",
  },
  {
    id: 4,
    category: "Apple Watch Ultra",
    title: "AVENTURA\nSIN FRONTERAS",
    description:
      "El reloj más resistente y avanzado para los que buscan superar todos los límites.",
    price: "s/ 600.00",
    image: "/inicio/head4.png?height=500&width=600",
    buttonText: "Explorar",
  },
];

export const patriasOffers = [
  {
    id: "poi15",
    name: "iPhone 15 Pro Max 256GB",
    category: "CELULARES",
    price: 999,
    originalPrice: 1299,
    image: "/productos/patrias/iPhone-15-Pro-Max-256GB.png",
    discount: 23,
    brand: "Apple",
    rating: 5,
    reviews: 234,
    stock: 5,
    isLimitedTime: true,
  },
  {
    id: "poi16",
    name: "MacBook Air M2 512GB",
    category: "LAPTOPS",
    price: 1199,
    originalPrice: 1499,
    image: "/productos/patrias/MacBook-Air-M2-512GB.png",
    discount: 20,
    brand: "Apple",
    rating: 5,
    reviews: 189,
    stock: 3,
    isLimitedTime: true,
  },
  {
    id: "poi17",
    name: "Samsung Galaxy S24 Ultra",
    category: "CELULARES",
    price: 899,
    originalPrice: 1199,
    image: "/productos/patrias/Samsung-Galaxy-S24-Ultra.png",
    discount: 25,
    brand: "Samsung",
    rating: 4,
    reviews: 156,
    stock: 8,
    isLimitedTime: true,
  },
  {
    id: "poi18",
    name: "Sony WH-1000XM5 Headphones",
    category: "AUDIO",
    price: 299,
    originalPrice: 399,
    image: "/productos/patrias/Sony-WH-1000XM5-Headphones.png",
    discount: 25,
    brand: "Sony",
    rating: 5,
    reviews: 298,
    stock: 12,
    isLimitedTime: true,
  },
];

export const products = [
  {
    id: "arz614",
    name: 'ASUS ROG Zephyrus G14 14"',
    category: "LAPTOPS",
    price: 5000,
    originalPrice: 5099,
    image: "/productos/header_ofert1.png?height=300&width=300",
    discount: 2,
    brand: "ASUS",
    rating: 5,
    reviews: 234,
    stock: 5,
    isLimitedTime: true,
  },
  {
    id: "vg15",
    name: "VICTUS Gaming 15.6 FHD",
    category: "LAPTOPS",
    price: 5400,
    originalPrice: 5700,
    image: "/productos/header_ofert2.png?height=300&width=300",
    discount: 5,
    brand: "HP",
    rating: 4,
    reviews: 176,
    stock: 6,
    isLimitedTime: true,
  },
  {
    id: "n5g",
    name: "NITRO 5 Gaming 15.6 FHD",
    category: "LAPTOPS",
    price: 4000,
    originalPrice: 4500,
    image: "/productos/header_ofert3.png?height=300&width=300",
    discount: 11,
    brand: "Acer",
    rating: 4,
    reviews: 205,
    stock: 7,
    isLimitedTime: true,
  },
  {
    id: "pcg5",
    name: "PC Gamer AMD Ryzen 5 5600X",
    category: "PC GAMING",
    price: 3200,
    originalPrice: 4000,
    image: "/productos/headofert1.png?height=300&width=300",
    discount: 20,
    brand: "AMD",
    rating: 5,
    reviews: 150,
    stock: 4,
    isLimitedTime: true,
  },
  {
    id: "sgdr",
    name: "Silla Gaming DXRacer Racing Series",
    category: "SILLAS GAMING",
    price: 399,
    originalPrice: 499,
    image: "/productos/sillas/silla3.png?height=300&width=300",
    discount: 20,
    brand: "DXRacer",
    rating: 4,
    reviews: 89,
    stock: 10,
    isLimitedTime: true,
  },
  {
    id: "sgdf",
    name: "Silla Gaming DXRacer Formula Series",
    category: "SILLAS GAMING",
    price: 79,
    originalPrice: 99,
    image: "/productos/sillas/silla1.png?height=300&width=300",
    discount: 20,
    brand: "DXRacer",
    rating: 4,
    reviews: 64,
    stock: 12,
    isLimitedTime: true,
  },
];

export const recommendedProducts = [
  {
    id: "cpsx1",
    name: "Smartphone Xiaomi Redmi Note 12 Pro",
    category: "SMARTPHONES",
    price: 299,
    originalPrice: 349,
    image: "/productos/audifonos/audifono1.png?height=150&width=150",
    discount: 14,
    brand: "Xiaomi",
    rating: 4,
    reviews: 120,
    stock: 10,
    isLimitedTime: false,
  },
  {
    id: "cpsx2",
    name: "Carga Inalámbrica Belkin BoostCharge",
    category: "ACCESORIOS",
    price: 199,
    originalPrice: 249,
    image: "/productos/audifonos/audifono2.png?height=150&width=150",
    discount: 20,
    brand: "Belkin",
    rating: 4,
    reviews: 45,
    stock: 15,
    isLimitedTime: true,
  },
  {
    id: "cpsx3",
    name: "Laptop HP Victus Gaming 15.6",
    category: "LAPTOPS",
    price: 899,
    originalPrice: 999,
    image: "/productos/audifonos/audifono3.png?height=150&width=150",
    discount: 10,
    brand: "HP",
    rating: 5,
    reviews: 78,
    stock: 7,
    isLimitedTime: true,
  },
  {
    id: "cpsx4",
    name: "Juego de 4K Resident Evil 4",
    category: "VIDEOJUEGOS",
    price: 1099,
    originalPrice: 1299,
    image: "/productos/audifonos/audifono4.png?height=150&width=150",
    discount: 15,
    brand: "Capcom",
    rating: 5,
    reviews: 321,
    stock: 20,
    isLimitedTime: false,
  },
  {
    id: "cpsx5",
    name: "Mochila Targus CityGear",
    category: "MOCHILAS",
    price: 49,
    originalPrice: 59,
    image: "/productos/audifonos/audifono5.png?height=150&width=150",
    discount: 17,
    brand: "Targus",
    rating: 4,
    reviews: 60,
    stock: 25,
    isLimitedTime: false,
  },
  {
    id: "cpsx6",
    name: "Mochila Targus CityGear",
    category: "MOCHILAS",
    price: 39,
    originalPrice: 59,
    image: "/productos/audifonos/audifono6.png?height=150&width=150",
    discount: 34,
    brand: "Targus",
    rating: 4,
    reviews: 40,
    stock: 18,
    isLimitedTime: true,
  },
];

export const allProducts = [
  ...laptops,
  ...audifonos, 
  ...televisores,
  ...Sillas,
  ...flashDeals,
  ...patriasOffers,
  ...products,
  ...recommendedProducts
]